CREATE TABLE INVOICE (
  ID INT NOT NULL AUTO_INCREMENT,
  EMPLOYEE_ID VARCHAR(30) NOT NULL,
  AMOUNT MEDIUMINT NOT NULL,
  CREATION_DATE DATETIME NOT NULL,
  UPDATE_DATE DATETIME NOT NULL,
  STATUS VARCHAR(30) NOT NULL,
  SETTLEMENT_NUMBER VARCHAR(10) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(26) NOT NULL,
  ACCEPTOR_ID VARCHAR(30),
  PAYER_ID VARCHAR(30),
  ARCHIVED TINYINT(1) NOT NULL,
  FILE_NAME VARCHAR(30),
  PRIMARY KEY(ID)
);