CREATE TABLE BILL (
 ID INT NOT NULL,
 EMPLOYEE_ID VARCHAR(30) NOT NULL,
 HOURS SMALLINT NOT NULL,
 SALARY SMALLINT NOT NULL,
 BRUTTO MEDIUMINT NOT NULL,
 NETTO MEDIUMINT NOT NULL,
 CREATION_DATA DATETIME NOT NULL,
 UPDATE_DATE DATETIME NOT NULL,
 STATUS VARCHAR(30) NOT NULL,
 SETTLEMENT_NUMBER VARCHAR(10) NOT NULL,
 ACCOUNT_NUMBER VARCHAR(26) NOT NULL,
 ACCEPTOR_ID VARCHAR(30),
 PAYER_ID VARCHAR(30),
 PROCESSED TINYINT(1) NOT NULL,
 PRIMARY KEY(ID)
);