CREATE TABLE SALARY (
  EMPLOYEE_ID VARCHAR(30) NOT NULL,
  SALARY SMALLINT NOT NULL,
  PRIMARY KEY(EMPLOYEE_ID)
  );

CREATE TABLE ACCOUNT_NUMBERS (
  EMPLOYEE_ID VARCHAR(30) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(26) NOT NULL,
  PRIMARY KEY(EMPLOYEE_ID)
);

CREATE TABLE HOURS (
 EMPLOYEE_ID VARCHAR(30) NOT NULL,
 DAY DATE NOT NULL,
 TASK VARCHAR(50),
 COUNT SMALLINT,
 PRIMARY KEY(EMPLOYEE_ID, DAY)
);

CREATE TABLE BILL (
 ID INT NOT NULL AUTO_INCREMENT,
 EMPLOYEE_ID VARCHAR(30) NOT NULL,
 HOURS SMALLINT NOT NULL,
 SALARY SMALLINT NOT NULL,
 BRUTTO MEDIUMINT NOT NULL,
 NETTO DOUBLE NOT NULL,
 CREATION_DATA DATETIME NOT NULL,
 UPDATE_DATE DATETIME NOT NULL,
 STATUS VARCHAR(30) NOT NULL,
 SETTLEMENT_NUMBER VARCHAR(10) NOT NULL,
 ACCOUNT_NUMBER VARCHAR(26) NOT NULL,
 ACCEPTOR_ID VARCHAR(30),
 PAYER_ID VARCHAR(30),
 PROCESSED TINYINT(1) NOT NULL,
 FROM_DATE DATE,
 TO_DATE DATE,
 INCOME_COSTS DOUBLE,
 TAX DOUBLE,
 PRIMARY KEY(ID)
);