CREATE TABLE SALARY (
  EMPLOYEE_ID VARCHAR(30) NOT NULL,
  SALARY SMALLINT NOT NULL,
  PRIMARY KEY(EMPLOYEE_ID)
  );

CREATE TABLE ACCOUNT_NUMBERS (
  EMPLOYEE_ID VARCHAR(30) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(26) NOT NULL,
  PRIMARY KEY(EMPLOYEE_ID)
);

CREATE TABLE HOURS (
 EMPLOYEE_ID VARCHAR(30) NOT NULL,
 DAY DATE NOT NULL,
 TASK VARCHAR(50),
 COUNT SMALLINT,
 PRIMARY KEY(EMPLOYEE_ID, DAY)
);
