CREATE TABLE SALARY (
  EMPLOYEE_ID VARCHAR(30) NOT NULL,
  SALARY SMALLINT NOT NULL,
  PRIMARY KEY(EMPLOYEE_ID)
  );

CREATE TABLE ACCOUNT_NUMBERS (
  EMPLOYEE_ID VARCHAR(30) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(26) NOT NULL,
  PRIMARY KEY(EMPLOYEE_ID)
);